### ISSUE TITLE
abort after a few rounds of game play: Assertion '*_head == _item' failed at pulse/mainloop.c:515, function cleanup_time_events(). 

### ISSUE THREAD

**Issue by XracerX** [nachomonkey/Interplanetary-Invaders#3]
$ python3 run_game.py 
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
[ after some minutes of game play ]
Assertion '*_head == _item' failed at pulse/mainloop.c:515, function cleanup_time_events(). Aborting.
Aborted (core dumped)

$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 32 (Thirty Two)
Release:	32
Codename:	ThirtyTwo

$ python -V
Python 3.8.3

**Comment by XracerX** [comment]
Seems very similar to this description https://bugs.launchpad.net/linuxmint/+bug/1451614

**Comment by nachomonkey** [comment]
Sorry, this is an upstream issue, won't fix
